version: "3"

services:
  backend:
    container_name: backend
    image: jhj967878/plantit:django
    volumes:
      - ./server:/project/server
    working_dir: /project/server
    command: gunicorn --bind 0:8000 server.wsgi:application
    expose:
      - 8000

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server:/project/server
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - backend